development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://prattleappserver.com/faye"
  secret_token: "48ee81e048d95e4dfd7c882024ef493050a754bfd48fde964adaaaa05b6f38fe"
  signature_expiration: 86400 # one hour
